### ISSUE TITLE
Rewards for DEV contribution have not been distributed

### ISSUE THREAD

**Issue by hdmiimdh** [NibiruChain/pricefeeder#41]
I wanted to kindly inquire about the status of the additional rewards mentioned in the conditions for the [Nibiru Incentivized Testnet 1](https://nibiru.fi/blog/posts/007-itn-1.html), specifically for developers who contributed by adding a datasource to the pricefeeder repository.

<img width="723" alt="Screenshot 2024-04-01 at 14 57 23" src="https://github.com/NibiruChain/pricefeeder/assets/27004732/bcca27d8-bb6f-43af-b8ae-3c1505d61003">

I have completed this contribution as per the outlined requirements and provided all necessary information as requested for the rewards to be sent to growth@nibiru.org. Here is the confirmation of my Merge Requests:

[Link to Merge Request #29](https://github.com/NibiruChain/pricefeeder/pull/29)
[Link to Merge Request #38](https://github.com/NibiruChain/pricefeeder/pull/38)

Despite submitting the contribution, I have not received any response nor observed any rewards for it. I wanted to kindly inquire whether the Nibiru team has plans to distribute these rewards or if there have been any updates regarding this matter.

cc @k-yang

**Comment by k-yang** [comment]
This is completed.

**Comment by hdmiimdh** [comment]
@k-yang

This was not taken into account otherwise our wallet won't claim 400 nibi as thousands of other wallets and it's enough to spend few minutes to understand it. It's very unfortunate to see such disrespect to ppl who contributed to the source code a year before listing. You had like 3-4 PR and ppl who opened them really have to email you every week without any feedback, attaching screenshots, passing KYC and do whatever else sh*t you asked for.

Whatever man I'll leave it on you. I am not gonna spend another second on this SCAM.
